### ISSUE TITLE
Update this pipeline

### ISSUE THREAD

**Issue by DanRunfola** [wmgeolab/gbAuth-ETL#1]
We need to fix this pipeline in a few ways (I think):
1) Right now, the geometry attribute table "ISO code in attribute table is GNB for all regions instead of region specific codes.".  In cases where no ISO code is provided for individual geometries, we should start replacing them with "Unknown".
2) We will need to re-run this after the above fix, and then make sure the pipeline is setup well.

**Comment by rohith4444** [comment]
Cross checked Every Thing. Its all good!
